kind: Service
apiVersion: v1
metadata:
  name: kinguin-api
spec:
  selector:
    app: kinguin-api
  ports:
  - protocol: TCP
    port: 9080
    nodePort: 30010
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kinguin-api
spec:
  selector:
      matchLabels:
        app: kinguin-api
  replicas: 1
  template:
    metadata:
      labels:
        app: kinguin-api
    spec:
      containers:
        - name: kinguin-api
          image: docker.io/damianeusz/kinguin-api:v3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9080
